// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NeverNull")]
[assembly: AssemblyDescriptionAttribute("A Option type that allows readable and bloat free null handling.")]
[assembly: GuidAttribute("1f08d66b-44d7-4616-a82e-250a3817adbd")]
[assembly: AssemblyProductAttribute("NeverNull")]
[assembly: AssemblyVersionAttribute("1.5.0")]
[assembly: AssemblyFileVersionAttribute("1.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.5.0";
    }
}
