// <auto-generated/>

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("NeverNull")]
[assembly: AssemblyDescription("A Option type that allows readable and bloat free null handling.")]
[assembly: Guid("1f08d66b-44d7-4616-a82e-250a3817adbd")]
[assembly: AssemblyProduct("NeverNull")]
[assembly: AssemblyVersion("1.5.0")]
[assembly: AssemblyFileVersion("1.5.0")]
namespace NeverNull.Properties {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.5.0";
    }
}
