// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NeverNull")]
[assembly: AssemblyProductAttribute("NeverNull")]
[assembly: AssemblyDescriptionAttribute("An Option type that allows readable and bloat free handling of null and 'magic values'.")]
[assembly: AssemblyVersionAttribute("3.0")]
[assembly: AssemblyFileVersionAttribute("3.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0";
    }
}
